### ISSUE TITLE
VMSUSB interrupt driven stacks only work for 8 bit status ids as coded.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/NSCLDAQ#100]
#### Background 
The VMUSB supplies registers that allow a 16 bit status id to be provided for interrupt triggered stacks and the range for allowed vectors supplied in the user configuration script is 0-0xffff which also supports 16 bit vectors.  The (current) VME standard, however allows modules to drive either 8 or 16 bit status ids on IACK cycles.   When the module drives an 8 bit status id, it will float the top 8 bits of the status id and  drive the bottom 8 bits.   In this case the 16 bit status id will look like 0xffnn where nn are the 8 bits driven by the module.

On the other hand, if a  module provides a 16 bit status id, all 16 bits of the status id will be driven.

Currently the source code in 12.0-main unconditionally sets the top 8 bits of the status id expeted to 0xff supporting, therefore, only 8 bit interrupters.

####  Proposed changes

*   Add a  new set of boolean options to  ```...vmusb/daqconfig/CStack.cpp```   which default to false (or possibly a list of bools parameter)
    * -ipl116bits
    * -ipl216bits
    * -ipl316bits
    * -ipl416bits
    * -ipl516bits
    * -ipl616bits
    * -ipl716bits

When setting up an interrupt triggered stack for a specific level, the value of the appropriate option is consulted and:

*  If true, all 16 bits of the status Id are programmed into the vector low and high registered.
*  if false (the default), the top 8 bits of the status id are set to 0xff in anticipation of those lines being floated by the interruptor.

Supporting an edge case where the same stack is triggered by several modules, some of them 16 bit some 8 bit requires the trick of setting the status ids on the 16 bit modules to 0xffnn and the ones on the 8 bit modules to 0xnn and specifying to the configuration that the ipl is 8 bits.

This edge case is not an abuse of the system.   Imagine that you have several modules, they can all interrupt when they need servicing but you want to empty all modules at that time so you write a stack to do so and then set up all modules to the same IPL/status id and trigger that stack on that interrupt.  If, as Mesytec modules can, all modules can supply a synchronized timestamp in each event, the resulting soup can be untangled into events.

**Comment by geniejhang** [comment]
I think the default behavior should be true because all the other people using interrupt must be undisturbed by the changes.
We just add the option and write it down specifically on the MDPP documentation.

**Comment by rfoxkendo** [comment]
The *16bits options may need a better name....how about an enumerated parameter:
-ipl*topbits one of ones, zeroes, fromvector

**Comment by rfoxkendo** [comment]
Document that for modules that only support 8 bit interrupters, such as Mestec MxDC32 and MDPP32 modules, the top 8 bits of the vector specifie to the VMSUB must be set. E.g. if you program an MADC32 with a vector of 0xnn specify to the VMSUB a vector of 0xffnn

Maybe add word for each module we support in its documentation describing the VMUSB needs for using it to trigger a stack on interrutps.
