### ISSUE TITLE
Refactor DDAS format and NSCLDAQ FragmentIndex

### ISSUE THREAD

**Issue by aschester** [FRIBDAQ/NSCLDAQ#121]
Both NSCLDAQ and SpecTcl rely on some classes for storing DDAS hit information and unpacking data into this storage. Programs like the ddasdumper use a modified version of the storage class to write data to ROOT trees. The code to do all this is maintained independently in multiple places including the ddas/format directory.

We need one version of these classes which everyone - NSCLDAQ, SpecTcl, users - can access and use. Similar to the unifiedformat library, the DDAS format stuff can exist on its own and be incorp'd into NSCLDAQ builds. Note that this may end up breaking a lot of user code which relies on the current headers and libs... but is probably long term less painful.

Another shared piece of code between NSCLDAQ and SpecTcl is the FragmentIndexer - NSCLDAQ in fact uses the SpecTcl version. This could probably go into the unifiedformat library as it has to do with breaking up ring item bodies into fragments (individual hits).

These are medium-term goals for a 12.1 bullseye release.

**Comment by aschester** [comment]
This has been done for DDASHit and the DDASHitUnpacker, but the FragmentIndex is a bit tough. Its really related to event building, not anything specific for DDAS, and is probably too general to stuff into a repo with things related to handling DDAS data. I'm also a bit loathe to make _yet another_ incorp. It is probably worth, at some point, to revisit the git submodule business... if we can live with the source tree being writable which I suspect is _generally_ true.

**Comment by rfoxkendo** [comment]
This has been added to unified format 2.1 - make FragmentIndex in our source tree a wrapper.

**Comment by rfoxkendo** [comment]
Note in the future (maybe another issue) use ufmt::CPhysicsEvent::getFragments instead of the bare FragmentIndex.

**Comment by rfoxkendo** [comment]
or NSCLDAQ, the simplest is to:
*  Remove the libFragmentIndex.la and its sources from main/daq/eventbuilde.
*  Remvoe fragment.h and where it's used:
```c++
#include <fragment.h>
using namespace ufmt;
```

**Comment by rfoxkendo** [comment]
I have removed all fragment index and fragment.h references and fixed up namespaces in affected files.  If you log and look for "Issue # 121" you'll get the commits...sadly I accidentally put a space between the # and 1 in my template commit file which prevents assocation of the commits with this issue.
