### ISSUE TITLE
Sorting ringbuffer not always created

### ISSUE THREAD

**Issue by aschester** [FRIBDAQ/NSCLDAQ#154]
ddasSort creates the sink ring for the sorter if it does not exist. This often fails, causing the DAQ to crash on start. To fix this one has to create the ringbuffer by hand or restart the ReadoutShell until the automatic creation works.

**Comment by rfoxkendo** [comment]
ddasSort (see ddasSort.cpp in main/ddas/readout uses

CRingBuffer::createAndProduce to create and produce into its sink ring.  This shouild throw an exception if it fails which is caught by the catch block below it The catch blocks all produce errors.  Are there error messages when this occurs?  If so what?

**Comment by aschester** [comment]
![readout_error](https://github.com/user-attachments/assets/19755f3c-0fe6-4025-a56a-6419acc69d34)

I click start to boot the crates. All crates boot without an issue, no reported errors and appear ready to take data. In this case, the sort ring on daqcompute003 was not created, and when beginning a run the above error occurs immediately. The other data sources continue sending data. Restarting the readoutshell and rebooting the system will _usually_ fix the issue after a couple of tries. I don't see any other errors on the data source tabs, just whats shown here.

**Comment by aschester** [comment]
Fixed by @rfoxkendo in rfoxkendo/issue154 - backporting to 12.0 still needed (if desired, probably a good idea)

**Comment by aschester** [comment]
backported to 12.0 by #166 , closing
