### ISSUE TITLE
Allow users to specify ringbuffer size

### ISSUE THREAD

**Issue by aschester** [FRIBDAQ/NSCLDAQ#157]
For some applications larger ringbuffer sizes are desired. The readout code will set up its own ringbuffers with the default 8 MB size which may be too small. A set of parameters for ddasReadout to override default ringbuffer sizes would be nice to have.

**Comment by rfoxkendo** [comment]
See issue #99 
and issue #48

These are implemented in 12.1-dev (main/base/CRingBuffer.cpp and main/base/CRemoteAccess.cpp).


Note that there are no less than three ringbuffers sizes that need to be considered:

1. The size of the the DDASReadout ouptut ring
2. The size of the ring created by ddasSorter
3. The size of proxy rings that are created by users getting remote data....and this one is not controllable by the ddasReadout script as proxy rings can be created at any time by the user.

Issue #48 - Supports an environment variable to override the default ringbuffer size. (NSCLDAQ_DEFAULT_RINGMBYTES)
Issue #99 - Supports an environment variable that sets the default proxy ring buffer size (NSCLDAQ_DEFAULT_PROXYMB)

Do these satisfy the issue - along with documentation in DDAS stuff to tell people about this?

**Comment by aschester** [comment]
Looks good to me!
