### ISSUE TITLE
Debugging mode for qtscope

### ISSUE THREAD

**Issue by aschester** [FRIBDAQ/NSCLDAQ#16]
qtscope debugging output configurable with environment variable similar to offline mode

**Comment by rfoxkendo** [comment]
https://docs.python.org/3/library/logging.html

(tutorial:  https://docs.python.org/3/howto/logging.html)

Might be really useful and give you some granularity - -the env variable could be the logging threshold then you'd get the verbosity level called for at any given time depending on what is logged at what level and what level is set as the threshold.

**Comment by aschester** [comment]
I have actually been implementing the logging exactly the way you suggest. I added a 12.1 milestone to this, which is almost done. Hopefully next week when I am not so busy with user support...
