### ISSUE TITLE
Delay datasource 0 at the end never ends with 12.1-pre2

### ISSUE THREAD

**Issue by geniejhang** [FRIBDAQ/NSCLDAQ#181]
S800 DAQ has three datasources, VMUSB, delay, and CCUSB.
Delay is set with 1000ms at the start and 0ms at the end.

It starts fine with 1000ms delay at the start, but 0ms at the end hangs there and never go forward from there.
So, CCUSB never end hanging at delay 0ms.

Workaround for it for now is to set the delay with 1ms.

**Comment by rfoxkendo** [comment]
Seem fixed?
