### ISSUE TITLE
docs for unglom and reglom

### ISSUE THREAD

**Issue by aschester** [FRIBDAQ/NSCLDAQ#195]
offlinereglom GUI use is documented but the unglom and reglom programs are not. Missing docs for users who want to automate rebuilding events offline using these programs without the GUI.

**Comment by rfoxkendo** [comment]
Grabbing.

**Comment by rfoxkendo** [comment]
Unglom docs were actually written just not included in the docbuild Makfefile.am

**Comment by rfoxkendo** [comment]
Added docs for Unglom and reglom.

**Comment by rfoxkendo** [comment]
Doing pull from rfoxkendo/issue195 -> 12.1-dev
