### ISSUE TITLE
Cookbook for process missing a makefile.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/NSCLDAQ#206]
Not in the repository so  it does not get installed.

**Comment by rfoxkendo** [comment]
See as well if 12.x needs the Makefiles to be adjusted for unfied format.

**Comment by aschester** [comment]
if process is intended to use ufmt, should it just be part of ufmt (which already has evtdump)?

**Comment by aschester** [comment]
closed #212 #211 , note that process _does not_ use ufmt library. See ufmt evtdump example for that.

**Comment by rfoxkendo** [comment]
> if process is intended to use ufmt, should it just be part of ufmt (which already has evtdump)?

Not necessarily.  For example NSCLDAQ  itself uses ufmt as a reductio ad absurdum.
