### ISSUE TITLE
offlinereglom requires more than one data source 

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/NSCLDAQ#82]
This is problematic for regloming data DDAS single crate systems. (Inside FRIB) See the helpme ticket:

https://help.frib.msu.edu/staff/index.php?/Tickets/Ticket/View/855032/inbox/3/-1/-1/0

**Comment by aschester** [comment]
Merge #83 and #85 for 11.3 and 12.0 branches, respectively.
